name: List Versions of ECS With Default Region By KooCLI
on:
  push:
    branches:
        master-dev
jobs:
  List-Versions:
    runs-on: windows-latest
    steps:
      # 代码检出
      - name: checkout
        uses: actions/checkout@v2
        
      - run: echo $HOSTTYPE
      
      - name: List Versions
        uses: ./
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'cn-north-4'
          command_list: 'hcloud ECS NovaListVersions'
          
      - run: hcloud version
