name: List Versions of ECS With Default Region By KooCLI
on:
  push:
    branches:
        master-dev
jobs:
  List-Versions:
    runs-on: windows-latest
#     runs-on: macos-latest
#     runs-on: ubuntu-latest  修改chmod方法  使用命令给777权限
    steps:
      # 代码检出
      - name: checkout
        uses: actions/checkout@v2
        
#       - run: echo $HOSTTYPE
#       - run: curl -sSL https://hwcloudcli.obs.cn-north-1.myhuaweicloud.com/cli/latest/hcloud_install.sh -o ./hcloud_install.sh
#       - run: sudo bash ./hcloud_install.sh -y
#       - run: export STACK=hcloud-toolkit
#       - run: sudo hcloud version
#       - run: sudo hcloud ECS NovaListVersions

#       - run: tree C://windows//hcloud
#       - run: hcloud version
      
      - name: List Versions
        uses: ./
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'cn-north-4'
          command_list: 'hcloud ECS NovaListVersions'
          
      - run: hcloud version
